.build:
  image: docker:18
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile -t $DOCKERHUB_CSV_TO_SPOTIFY_IMAGE .
    - echo $DOCKERHUB_PASSWORD | docker login --username="$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_CSV_TO_SPOTIFY_IMAGE"
    - docker logout

build-production:
  extends: .build
  environment:
    name: production
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"

.aws-beanstalk:
  stage: deploy
  image: garland/aws-cli-docker:latest
  script:
    - sh -c "aws configure set region $AWS_REGION_CSV_TO_SPOTIFY && aws elasticbeanstalk update-environment --environment-name $AWS_ENV_NAME_CSV_TO_SPOTIFY --version-label $AWS_VERSION_CSV_TO_SPOTIFY > /dev/null 2>&1"

aws-beanstalk-production:
  extends: .aws-beanstalk
  environment:
    name: production
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
