.build:
  image: docker:18
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile -t $DOCKERHUB_CSV_TO_SPOTIFY_IMAGE .
    - echo $DOCKERHUB_PASSWORD | docker login --username="$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_CSV_TO_SPOTIFY_IMAGE"
    - docker logout

build-production:
  extends: .build
  environment:
    name: production
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
